<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../.resources/report.css" type="text/css"/><link rel="shortcut icon" href="../.resources/report.gif" type="image/gif"/><title>Exceptions.java</title><link rel="stylesheet" href="../.resources/prettify.css" type="text/css"/><script type="text/javascript" src="../.resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../.sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">rxjava</a> &gt; <a href="index.source.html" class="el_package">rx.exceptions</a> &gt; <span class="el_source">Exceptions.java</span></div><h1>Exceptions.java</h1><pre class="source lang-java linenums">/**
 * Copyright 2014 Netflix, Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package rx.exceptions;

import java.util.*;

import rx.Observer;
import rx.annotations.Experimental;

/**
 * Utility class with methods to wrap checked exceptions and
 * manage fatal and regular exception delivery.
 */
public final class Exceptions {
    /** Utility class, no instances. */
<span class="nc" id="L29">    private Exceptions() {</span>
<span class="nc" id="L30">        throw new IllegalStateException(&quot;No instances!&quot;);</span>
    }

    /**
     * Convenience method to throw a {@code RuntimeException} and {@code Error} directly
     * or wrap any other exception type into a {@code RuntimeException}.
     * @param t the exception to throw directly or wrapped
     * @return because {@code propagate} itself throws an exception or error, this is a sort of phantom return
     *         value; {@code propagate} does not actually return anything
     */
    public static RuntimeException propagate(Throwable t) {
        /*
         * The return type of RuntimeException is a trick for code to be like this:
         * 
         * throw Exceptions.propagate(e);
         * 
         * Even though nothing will return and throw via that 'throw', it allows the code to look like it
         * so it's easy to read and understand that it will always result in a throw.
         */
<span class="fc bfc" id="L49" title="All 2 branches covered.">        if (t instanceof RuntimeException) {</span>
<span class="fc" id="L50">            throw (RuntimeException) t;</span>
<span class="pc bpc" id="L51" title="1 of 2 branches missed.">        } else if (t instanceof Error) {</span>
<span class="nc" id="L52">            throw (Error) t;</span>
        } else {
<span class="fc" id="L54">            throw new RuntimeException(t);</span>
        }
    }
    /**
     * Throws a particular {@code Throwable} only if it belongs to a set of &quot;fatal&quot; error varieties. These
     * varieties are as follows:
     * &lt;ul&gt;
     * &lt;li&gt;{@link OnErrorNotImplementedException}&lt;/li&gt;
     * &lt;li&gt;{@link OnErrorFailedException}&lt;/li&gt;
     * &lt;li&gt;{@code StackOverflowError}&lt;/li&gt;
     * &lt;li&gt;{@code VirtualMachineError}&lt;/li&gt;
     * &lt;li&gt;{@code ThreadDeath}&lt;/li&gt;
     * &lt;li&gt;{@code LinkageError}&lt;/li&gt;
     * &lt;/ul&gt;
     * This can be useful if you are writing an operator that calls user-supplied code, and you want to
     * notify subscribers of errors encountered in that code by calling their {@code onError} methods, but only
     * if the errors are not so catastrophic that such a call would be futile, in which case you simply want to
     * rethrow the error.
     *
     * @param t
     *         the {@code Throwable} to test and perhaps throw
     * @see &lt;a href=&quot;https://github.com/ReactiveX/RxJava/issues/748#issuecomment-32471495&quot;&gt;RxJava: StackOverflowError is swallowed (Issue #748)&lt;/a&gt;
     */
    public static void throwIfFatal(Throwable t) {
<span class="fc bfc" id="L78" title="All 2 branches covered.">        if (t instanceof OnErrorNotImplementedException) {</span>
<span class="fc" id="L79">            throw (OnErrorNotImplementedException) t;</span>
<span class="fc bfc" id="L80" title="All 2 branches covered.">        } else if (t instanceof OnErrorFailedException) {</span>
<span class="fc" id="L81">            throw (OnErrorFailedException) t;</span>
        }
        // values here derived from https://github.com/ReactiveX/RxJava/issues/748#issuecomment-32471495
<span class="fc bfc" id="L84" title="All 2 branches covered.">        else if (t instanceof StackOverflowError) {</span>
<span class="fc" id="L85">            throw (StackOverflowError) t;</span>
<span class="fc bfc" id="L86" title="All 2 branches covered.">        } else if (t instanceof VirtualMachineError) {</span>
<span class="fc" id="L87">            throw (VirtualMachineError) t;</span>
<span class="fc bfc" id="L88" title="All 2 branches covered.">        } else if (t instanceof ThreadDeath) {</span>
<span class="fc" id="L89">            throw (ThreadDeath) t;</span>
<span class="pc bpc" id="L90" title="1 of 2 branches missed.">        } else if (t instanceof LinkageError) {</span>
<span class="nc" id="L91">            throw (LinkageError) t;</span>
        }
<span class="fc" id="L93">    }</span>

    private static final int MAX_DEPTH = 25;

    /**
     * Adds a {@code Throwable} to a causality-chain of Throwables, as an additional cause (if it does not
     * already appear in the chain among the causes).
     *
     * @param e
     *         the {@code Throwable} at the head of the causality chain
     * @param cause
     *         the {@code Throwable} you want to add as a cause of the chain
     */
    public static void addCause(Throwable e, Throwable cause) {
<span class="fc" id="L107">        Set&lt;Throwable&gt; seenCauses = new HashSet&lt;Throwable&gt;();</span>

<span class="fc" id="L109">        int i = 0;</span>
<span class="fc bfc" id="L110" title="All 2 branches covered.">        while (e.getCause() != null) {</span>
<span class="pc bpc" id="L111" title="1 of 2 branches missed.">            if (i++ &gt;= MAX_DEPTH) {</span>
                // stack too deep to associate cause
<span class="nc" id="L113">                return;</span>
            }
<span class="fc" id="L115">            e = e.getCause();</span>
<span class="pc bpc" id="L116" title="1 of 2 branches missed.">            if (seenCauses.contains(e.getCause())) {</span>
<span class="nc" id="L117">                break;</span>
            } else {
<span class="fc" id="L119">                seenCauses.add(e.getCause());</span>
            }
        }
        // we now have 'e' as the last in the chain
        try {
<span class="fc" id="L124">            e.initCause(cause);</span>
<span class="nc" id="L125">        } catch (Throwable t) {</span>
            // ignore
            // the javadocs say that some Throwables (depending on how they're made) will never
            // let me call initCause without blowing up even if it returns null
<span class="fc" id="L129">        }</span>
<span class="fc" id="L130">    }</span>

    /**
     * Get the {@code Throwable} at the end of the causality-chain for a particular {@code Throwable}
     *
     * @param e
     *         the {@code Throwable} whose final cause you are curious about
     * @return the last {@code Throwable} in the causality-chain of {@code e} (or a &quot;Stack too deep to get
     *         final cause&quot; {@code RuntimeException} if the chain is too long to traverse)
     */
    public static Throwable getFinalCause(Throwable e) {
<span class="fc" id="L141">        int i = 0;</span>
<span class="fc bfc" id="L142" title="All 2 branches covered.">        while (e.getCause() != null) {</span>
<span class="pc bpc" id="L143" title="1 of 2 branches missed.">            if (i++ &gt;= MAX_DEPTH) {</span>
                // stack too deep to get final cause
<span class="nc" id="L145">                return new RuntimeException(&quot;Stack too deep to get final cause&quot;);</span>
            }
<span class="fc" id="L147">            e = e.getCause();</span>
        }
<span class="fc" id="L149">        return e;</span>
    }
    /**
     * Throws a single or multiple exceptions contained in the collection, wrapping it into
     * {@code CompositeException} if necessary.
     * @param exceptions the collection of exceptions. If null or empty, no exception is thrown.
     * If the collection contains a single exception, that exception is either thrown as-is or wrapped into a
     * CompositeException. Multiple exceptions are wrapped into a CompositeException.
     * @since 1.1.0
     */
    public static void throwIfAny(List&lt;? extends Throwable&gt; exceptions) {
<span class="pc bpc" id="L160" title="1 of 4 branches missed.">        if (exceptions != null &amp;&amp; !exceptions.isEmpty()) {</span>
<span class="fc bfc" id="L161" title="All 2 branches covered.">            if (exceptions.size() == 1) {</span>
<span class="fc" id="L162">                Throwable t = exceptions.get(0);</span>
                // had to manually inline propagate because some tests attempt StackOverflowError 
                // and can't handle it with the stack space remaining
<span class="pc bpc" id="L165" title="1 of 2 branches missed.">                if (t instanceof RuntimeException) {</span>
<span class="fc" id="L166">                    throw (RuntimeException) t;</span>
<span class="nc bnc" id="L167" title="All 2 branches missed.">                } else if (t instanceof Error) {</span>
<span class="nc" id="L168">                    throw (Error) t;</span>
                } else {
<span class="nc" id="L170">                    throw new RuntimeException(t);</span>
                }
            }
<span class="fc" id="L173">            throw new CompositeException(</span>
                    &quot;Multiple exceptions&quot;, exceptions);
        }
<span class="fc" id="L176">    }</span>
    
    /**
     * Forwards a fatal exception or reports it along with the value
     * caused it to the given Observer.
     * @param t the exception
     * @param o the observer to report to
     * @param value the value that caused the exception
     * @since (if this graduates from Experimental/Beta to supported, replace this parenthetical with the release number)
     */
    @Experimental
    public static void throwOrReport(Throwable t, Observer&lt;?&gt; o, Object value) {
<span class="fc" id="L188">        Exceptions.throwIfFatal(t);</span>
<span class="fc" id="L189">        o.onError(OnErrorThrowable.addValueAsLastCause(t, value));</span>
<span class="fc" id="L190">    }</span>
    /**
     * Forwards a fatal exception or reports it to the given Observer.
     * @param t the exception
     * @param o the observer to report to
     * @since (if this graduates from Experimental/Beta to supported, replace this parenthetical with the release number)
     */
    @Experimental
    public static void throwOrReport(Throwable t, Observer&lt;?&gt; o) {
<span class="fc" id="L199">        Exceptions.throwIfFatal(t);</span>
<span class="fc" id="L200">        o.onError(t);</span>
<span class="fc" id="L201">    }</span>
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.eclemma.org/jacoco">JaCoCo</a> 0.7.1.201405082137</span></div></body></html>